baseURL: https://www.neuralia.co/
languageCode: en-us
title: neuralia.co
theme: "PaperMod"
paginate: 8
defaultContentLanguage: fr
#copyright: Neuralia.co 
displayFullLangName: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  fr:
    weight: 10
    languageName: Fr 🇫🇷
    profileMode:
      enabled: true
      title: neuralia.co
      subtitle: "Datascience, Machine Learning, API, Process Automatisés, Dev-Ops"
      imageUrl: ./images/logo.webp
      imageUrlLight: ./images/logo_light.webp 
      imageWidth: 200
      imageHeight: 200
      imageTitle: "Skwych, la mascotte de Neuralia.co"
      buttons:
        - name: mission
          url: /mission
    
  en:
    weight: 20
    languageName: En 🇬🇧
    profileMode:
      enabled: true
      title: neuralia.co
      subtitle: "Datascience, Machine Learning, API, Automated Process, Dev-Ops"
      imageUrl: ./images/logo.webp
      imageUrlLight: ./images/logo_light.webp 
      imageWidth: 200
      imageHeight: 200
      imageTitle: "Skwych, Neuralia.co's mascot"
      buttons:
        - name: mission
          url: /en/mission
  
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: neuralia.co
  description: "Datascience, Machine Learning, API, Automated Process, Dev-Ops"
  keywords: [Tech, DataScience, Machine Learning, API, DevOps, Entrepreneurship]
  author: ["Vincent Porte", "Amaury Leproux"] # multiple authors
  images: ["profile.png"]
  DateFormat: "2 January, 2006"
  defaultTheme: dark #auto # dark, light
  disableThemeToggle: false
  displayFullLangName: true
  ShowCanonicalLink: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  relativeURLs: true
  imagePreview: true

  #navigation:
  #  search: Rechercher

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: ./images/logo_bleu_64_fond_blanc.png
    favicon16x16: ./images/logo_bleu_16_fond_blanc.png
    favicon32x32: ./images/logo_bleu_32_fond_blanc.png
    apple_touch_icon: ./images/logo_bleu_180_fond_blanc.png

  label:
    text: " "
    icon: ./images/logo_blanc_64.png
    iconHeight: 32

 
  homeInfoParams:
    Title: Neuralia.co
    Content: Datascience, Machine Learning, API, Automated Process, Dev-Ops

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/company/neuralia-co"
    - name: github
      url: "https://github.com/organizations/neuralia-co"
    - name: instagram
      url: "https://instagram.com/neuralia_co"
    - name: spotify
      url: "https://open.spotify.com/show/7vx463HpANvyI7cI2S6o83"
    - name: email
      url: "mailto:contact@neuralia.co"
    

  cover:
      hidden: true # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: true # hide on single page

 # for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

#menu:
#  main:
#    - identifier: 
#      name: mission
#      url: /mission
#      weight: 10
#    - identifier: 
#      name: team
#      url: /team
#      weight: 20
#    - identifier: 
#      name: portfolio
#      url: /portfolio
#      weight: 30
